#
# prepares and runs gdunit4 tests
#

name: "Run gdUnit4 tests"
description: "Run gdunit4 tests"
inputs:
  binary:
    description: "The path to the godot binary"
    required: true
outputs: {} # no outputs

runs:
  using: "composite"
  steps:
    - name: Re-import project files
      shell: pwsh
      run: |
        pwd
        dir
        dir Godot_v4.2.1-stable_win64.exe

        $cli = $Env:GODOT_BIN + " --headless --editor --quit-after 60 ."
        echo $cli
        $cli
      env:
        GODOT_BIN: "${{ inputs.binary }}"
    # - name: Run tests
    #   shell: pwsh
    #   run: |
    #     & addons/gdUnit4/runtest.cmd --continue --add test
    #   env:
    #     GODOT_BIN: "${{ inputs.binary }}"
