#
# prepares and runs gdunit4 tests
#

name: "Run gdUnit4 tests"
description: "Run gdunit4 tests"
inputs:
  binary:
    description: "The path to the godot binary"
    required: true
outputs: {} # no outputs

runs:
  using: "composite"
  steps:
    - name: Re-import project files
      shell: pwsh
      run: |
        Start-Process -FilePath $Env:GODOT_BIN -ArgumentList "--headless --editor --quit-after 60 ." -Wait
      env:
        GODOT_BIN: "${{ inputs.binary }}"
    - name: Run tests
      shell: pwsh
      run: |
        Start-Process -FilePath "addons/gdUnit4/runtest.cmd" -ArgumentList "--continue --add test" -Wait
      env:
        GODOT_BIN: "${{ inputs.binary }}"
