#
# downloads the godot export templates and adds it to the export templates folder
#

name: "Download Godot Export Template"
description: "Downloads the Godot export templates and makes them available for the godot bin"
inputs:
  version:
    description: "The version of Godot to download"
    required: true
    default: "4.2.1-stable"
outputs: {}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -L https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz -o templates.zip
        unzip templates.zip
      env:
        GODOT_VERSION: ${{ inputs.version }}
    - shell: bash
      run: |
        template_directory=${GODOT_VERSION//-/.}
        echo "${HOME}/.local/share/godot/templates/${template_directory}"
        mkdir -p "${HOME}/.local/share/godot/templates/${template_directory}"
        mv templates/* "${HOME}/.local/share/godot/templates/${template_directory}/"
      env:
        GODOT_VERSION: ${{ inputs.version }}

    # Windows: %APPDATA%\Godot\templates\<version>\
    # Linux: $HOME/.local/share/godot/templates/<version>/
    # macOS: $HOME/Library/Application Support/Godot/templates/<version>/

