#
# downloads the godot export templates and adds it to the export templates folder
#

name: "Download Godot Export Template"
description: "Downloads the Godot export templates and makes them available for the godot bin"
inputs:
  version:
    description: "The version of Godot to download"
    required: true
    default: "4.2.1-stable"
outputs: {}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -L https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_${GODOT_VERSION}_export_templates.tpz -o templates.zip
        unzip templates.zip
        ls -lah
      env:
        GODOT_VERSION: ${{ inputs.version }}
    # - shell: bash
    #   run: |
    #     mkdir -p ~/.local/share/godot/templates/$GODOT_VERSION
    #     mv templates/* ~/.local/share/godot/templates/$GODOT_VERSION
    #     ls -lah ~/.local/share/godot/templates/$GODOT_VERSION

    # Windows: %APPDATA%\Godot\templates\<version>\
    # Linux: $HOME/.local/share/godot/templates/<version>/
    # macOS: $HOME/Library/Application Support/Godot/templates/<version>/

