#
# exports the compiled game for the given export preset with the given godot binary
#

name: "Run export-release"
description: "Run export-release"
inputs:
  binary:
    description: "The path to the godot binary"
    required: true
  preset:
    description: "The export preset to use"
    required: true
  filename:
    description: "The filename of the exported game"
    required: true
  retention:
    description: "The number of days to keep the build"
    required: true
    default: "3"
outputs: {} # no outputs

runs:
  using: "composite"
  steps:
    - name: Export release
      shell: bash
      run: |
        mkdir .ci-build
        $GODOT_BIN --headless --export-release "${PRESET}" ".ci-build/${FILENAME}"
      env:
        GODOT_BIN: ${{ inputs.binary }}
        PRESET: ${{ inputs.preset }}
        FILENAME: ${{ inputs.filename }}
    - name: Archive build
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.filename }}.zip
        path: .ci-build/**/*
        retention-days: ${{ inputs.retention }}
        if-no-files-found: error