#
# downloads the godot binary
#

name: "Download Godot Binary"
description: "Downloads the godot binary for the given os and and godot verison"
inputs:
  version:
    description: "The version of Godot to download"
    required: true
    default: "4.2.1"
  os:
    description: "The os to download the binary for"
    required: true
    default: "linux"
outputs:
  godot-bin:
    description: "The path to the Godot binary"
    value: ${{ steps.download.outputs.godot-bin }}

runs:
  using: "composite"
  steps:
    - id: download
      uses: ./.github/actions/${{ inputs.os }} /download-godot
      with: 
        version: ${{ inputs.version }}
  