#
# downloads the godot binary for linux
# and exports the path to the binary as an environment variable
#

name: "Download Godot Binary"
description: "Downloads the godot binary for the given os and and godot verison"
inputs:
  version:
    description: "The version of Godot to download"
    required: true
    default: "4.2.1"
  os:
    description: "The os to download the binary for"
    required: true
    default: "linux"
outputs:
  godot-bin:
    description: "The path to the Godot binary"
    value: ${{ steps.download.outputs.godot-bin }}


runs:
  using: "composite"
  steps:
    - id: download
      shell: bash
      run: |
        curl -LO https://github.com/godotengine/godot-builds/releases/download/$GODOT_VERSION-stable/Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
        unzip Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
        chmod +x Godot_v$GODOT_VERSION-stable_linux.x86_64
        echo "godot-bin=$PWD/Godot_v$GODOT_VERSION-stable_linux.x86_64" >> $GITHUB_OUTPUT
      env:
        GODOT_VERSION: ${{ inputs.version }}
