#
# downloads the godot binary
#

name: "Download Godot Binary"
description: "Downloads the godot binary for the given os and and godot verison"
inputs:
  version:
    description: "The version of Godot to download"
    required: true
    default: "4.2.1-stable"
  os:
    description: "The os to download the binary for"
    required: true
    default: "linux"
outputs:
  godot-bin:
    description: "The path to the Godot binary"
    value: ${{ steps.binary.outputs.godot-bin }}

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.os == 'linux' }}
      id: download-linux
      uses: ./.github/actions/linux/download-godot
      with: 
        version: ${{ inputs.version }}
    - if: ${{ inputs.os == 'mac' }}
      id: download-mac
      uses: ./.github/actions/mac/download-godot
      with: 
        version: ${{ inputs.version }}
    - if: ${{ inputs.os == 'windows' }}
      id: download-windows
      uses: ./.github/actions/windows/download-godot
      with: 
        version: ${{ inputs.version }}
    - id: binary
      shell: bash
      run: |
        if [ -n "${{ steps.download-linux.outputs.godot-bin }}" ]; then
          echo "godot-bin=${{ steps.download-linux.outputs.godot-bin }}" >> $GITHUB_OUTPUT
        fi
        if [ -n "${{ steps.download-mac.outputs.godot-bin }}" ]; then
          echo "godot-bin=${{ steps.download-mac.outputs.godot-bin }}" >> $GITHUB_OUTPUT
        fi
        if [ -n "${{ steps.download-windows.outputs.godot-bin }}" ]; then
          echo "godot-bin=${{ steps.download-windows.outputs.godot-bin }}" >> $GITHUB_OUTPUT
        fi