#
# downloads the godot binary for linux
# and exports the path to the binary as an environment variable
#

name: "Download Godot Binary"
description: "Downloads the Godot binary for mac and exports the path to the binary as an environment variable"
inputs:
  version:
    description: "The version of Godot to download"
    required: true
    default: "4.2.1"
outputs:
  godot-bin:
    description: "The path to the Godot.app"
    value: ${{ steps.download.outputs.godot-bin }}

runs:
  using: "composite"
  steps:
    - id: download
      shell: pwsh
      run: |
        $name = "Godot_v" + $Env:GODOT_VERSION + "-stable_win64"
        $zip = $name + ".exe.zip"
        $bin = $name + ".exe" 
        $download_url = "https://github.com/godotengine/godot-builds/releases/download/" + $Env:GODOT_VERSION + "-stable/" + $zip
        $local_full_path_to_bin = Join-Path -Path $PWD $name $bin
        $output = "godot-bin=" + $local_full_path_to_bin
       
        echo $name
        echo $zip
        echo $bin
        echo $download_url
        echo $local_full_path_to_bin
        echo $output

        curl -LO $download_url
        unzip $zip 
        echo $output >> $Env:GITHUB_OUTPUT
      env:
        GODOT_VERSION: ${{ inputs.version }}