name: Run a multi os build on pushes to main
on:
  workflow_dispatch:
  push:
    branches:
      - main
# check write permissions are required for junit step
permissions:
    contents: read
    checks: write
    id-token: write
jobs:
  # thanks to https://www.jitsejan.com/use-github-actions-with-json-file-as-matrix
  configure-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load-matrix.outputs.json }}
    steps:
      - uses: actions/checkout@v2
      - id: load-matrix
        run: echo "json=$(jq -c . < .github/workflows/matrix.json)" >> $GITHUB_OUTPUT
  build:
    needs: configure-matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.configure-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 900
    steps:
      - uses: actions/checkout@v2      
      - id: download
        name: download godot
        uses: ./.github/actions/_all/download-godot
        with:
          os: ${{ matrix.os }}
          version: ${{ vars.GODOT_VERSION }}
      - name: download export templates
        uses: ./.github/actions/_all/download-export-templates
        with:
          os: ${{ matrix.os }}
          version: ${{ vars.GODOT_VERSION }}
      