name: Run a multi os build on pushes to main
on:
  workflow_dispatch:
  push:
    branches:
      - main
# check write permissions are required for junit step
permissions:
    contents: read
    checks: write
    id-token: write
jobs:
  # thanks to https://www.jitsejan.com/use-github-actions-with-json-file-as-matrix
  configure-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load-matrix.outputs.json }}
    steps:
      - uses: actions/checkout@v2
      - id: load-matrix
        run: echo "json=$(jq -c . < .github/workflows/matrix.json)" >> $GITHUB_OUTPUT
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ needs.configure-matrix.outputs.matrix }}"
      - name: Print matrix
        run: echo "${{ fromJson(needs.configure-matrix.outputs.matrix) }}"
      
  build:
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.configure-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 900
    if: ${{ matrix.enabled }}
    steps:
      - uses: actions/checkout@v2
      # - id: download
      #   name: download godot
      #   uses: ./.github/actions/linux/download-godot
      #   with:
      #     version: ${{ vars.GODOT_VERSION }}
      # - name: run tests
      #   uses: ./.github/actions/linux/run-gdunit4
      #   with:
      #     binary: ${{ steps.download.outputs.godot-bin }}
      # - name: Publish Test Report
      #   uses: mikepenz/action-junit-report@v4
      #   if: success() || failure() # always run even if the previous step fails
      #   with:
      #     report_paths: '**/reports/report_1/**/results.xml'
      #     require_tests: true
      #     require_passed_tests: true
      #     include_passed: true