#
# build the game on pushes to main
#

name: Run a multi os build on pushes to main
on:
  workflow_dispatch:
  push:
    branches:
      - main
# check write permissions are required for junit step
permissions:
    contents: read
    checks: write
    id-token: write
jobs:
  # thanks to https://www.jitsejan.com/use-github-actions-with-json-file-as-matrix
  load-configuration:
    runs-on: ubuntu-latest
    outputs:
      configuration: ${{ steps.load-configuration.outputs.json }}
    steps:
      - uses: actions/checkout@v2
      - id: load-configuration
        run: echo "json=$(jq -c . < .github/workflows/config.json)" >> $GITHUB_OUTPUT
  build-linux:
    needs: load-configuration
    runs-on: ${{ fromJson(needs.load-configuration.outputs.configuration).linux.runner }}
    timeout-minutes: 900
    steps:
      - uses: actions/checkout@v2      
      - id: download
        name: download godot
        uses: ./.github/actions/${{ fromJson(needs.load-configuration.outputs.configuration).linux.os }}/download-godot
        with:
          version: ${{ vars.GODOT_VERSION }}
      - name: download export templates
        uses: ./.github/actions/${{ fromJson(needs.load-configuration.outputs.configuration).linux.os }}/download-export-templates
        with:
          version: ${{ vars.GODOT_VERSION }}
      # - name: export game
      #   uses: ./.github/actions/${{ fromJson(needs.load-configuration.outputs.configuration).linux.os }}/export
      #   with:

      #     version: ${{ vars.GODOT_VERSION }}
