#
# execute gdunit4 tests on pushes to branches with pull requests
#

name: Run tests on pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
# check write permissions are required for junit step
permissions:
    contents: read
    checks: write
    id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2
      - id: download
        name: download godot
        uses: ./.github/actions/linux/download-godot
        with:
          version: ${{ vars.GODOT_VERSION }}
      - name: run tests
        uses: ./.github/actions/linux/run-gdunit4
        with:
          binary: ${{ steps.download.outputs.godot-bin }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/reports/report_1/**/results.xml'
          require_tests: true
          require_passed_tests: true
          include_passed: true