name: Run tests on pull request
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download godot
        uses: ./.github/actions/linux/download-godot
      - run: |
          env
          ${{ env.GODOT_BIN }} --version
      