name: Run tests on pull request
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: download
        name: download godot
        uses: ./.github/actions/linux/download-godot
        with:
          version: ${{ vars.GODOT_VERSION }}
      - run: |
          env
          echo ${{ steps.download.outputs.godot-bin }}
          ${{ env.GODOT_BIN }} --version
        env:
          GODOT_BIN: ${{ steps.download.outputs.godot-bin }}
          GODOT_VERSION: ${{ vars.GODOT_VERSION }}
