name: Run tests on pull request (on windows runners for reference!)
on:
  workflow_dispatch:
permissions:
    contents: read
    checks: write
    id-token: write
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - id: download
        name: download godot
        uses: ./.github/actions/windows/download-godot
        with:
          version: ${{ vars.GODOT_VERSION }}
      - name: run tests
        uses: ./.github/actions/windows/run-gdunit4
        with:
          binary: ${{ steps.download.outputs.godot-bin }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/reports/report_1/**/results.xml'
          require_tests: true
          require_passed_tests: true
          include_passed: true