name: Run tests on pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
# permissions are required for junit step
permissions:
    checks: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: download
        name: download godot
        uses: ./.github/actions/linux/download-godot
        with:
          version: ${{ vars.GODOT_VERSION }}
      - name: run tests
        uses: ./.github/actions/linux/run-gdunit4
        with:
          binary: ${{ steps.download.outputs.godot-bin }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/reports/report_1/**/results.xml'
          require_tests: true